export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'

export const UPDATE_STAKING_ACCOUNT = 'UPDATE_STAKING_ACCOUNT'

export const UPDATE_VALIDATORS = 'UPDATE_VALIDATORS'

export const UPDATE_SORTBY = 'UPDATE_SORTBY'

export const UPDATE_SELECTED_VALIDATORS = 'UPDATE_SELECTED_VALIDATORS'

export const UPDATE_ERA_ELECTION_STATUS = 'UPDATE_ERA_ELECTION_STATUS'

export const UPDATE_NOMINATING_STATUS = 'UPDATE_NOMINATING_STATUS'

export const UPDATE_EXISTENTIAL_DEPOSIT = 'UPDATE_EXISTENTIAL_DEPOSIT'

export const UPDATE_REFERENDUMS = 'UPDATE_REFERENDUMS'

export const UPDATE_DEMOCRACY = 'UPDATE_DEMOCRACY'

export const UPDATE_COUNCIL = 'UPDATE_COUNCIL'